---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

There is a place where the sidewalk ends  
And before the street begins,  
And there the grass grows soft and white,  
And there the sun burns crimson bright,  
And there the moon-bird rests from his flight  
To cool in the peppermint wind.  

Let us leave this place where the smoke blows black  
And the dark street winds and bends.  
Past the pits where the asphalt flowers grow  
We shall walk with a walk that is measured and slow,  
And watch where the chalk-white arrows go  
To the place where the sidewalk ends.  

Yes we'll walk with a walk that is measured and slow,  
And we'll go where the chalk-white arrows go,  
For the children, they mark, and the children, they know  
The place where the sidewalk ends.  
